[program:scheduler]
command=/bin/bash -c "while [ true ]; do (php artisan schedule:run --verbose --no-interaction &); sleep 60; done"
directory=/var/www/html
autostart=true
autorestart=true
user=docker
redirect_stderr=true
stdout_logfile=/var/log/supervisor/scheduler.log
