version: "3.8"

services:
  nginx:
    image: nginx:1.27-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - merchant_net

  app:
    build:
      context: ./docker/php-fpm
      dockerfile: production/Dockerfile
    restart: always
    user: "1000:988"
    volumes:
      - ./src:/var/www/html:delegated
      - ./docker/php-fpm/common/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/php-fpm/common/conf.d/security.ini:/usr/local/etc/php/conf.d/security.ini
    networks:
      - merchant_net


  redis:
    image: redis:alpine
    restart: always
    networks:
      - merchant_net


networks:
  merchant_net:
    driver: bridge
